### ISSUE TITLE
Do you have paper ?

### ISSUE THREAD

**Issue by Gatsby23** [arntanguy/kalman_lie#1]

**Comment by arntanguy** [comment]
This is not based on a specific paper, just a generic implementation of ekf algorithm with focus on lie algebra for pose estimation.
See https://github.com/mherb/kalman for more information.

This hasn't been extensively tested, but as far as I remember it worked.

**Comment by Gatsby23** [comment]
> This is not based on a specific paper, just a generic implementation of ekf algorithm with focus on lie algebra for pose estimation. See https://github.com/mherb/kalman for more information.
> 
> This hasn't been extensively tested, but as far as I remember it worked.

Thank you very much
